export {default as LikeIcon} from './like.svg';
export {default as CommentIcon} from './comments.svg';
export {default as AddIcon} from './add.svg';
export {default as CancelIcon} from './cancel.svg';
export {default as LikeFilledIcons} from './like-filled.svg';
export {default as HomeOutLined} from './home-outlined.svg';
export {default as HomeFilled} from './home-filled.svg';
export {default as PostOutLined} from './post-outlined.svg';
export {default as PostFilled} from './post-filled.svg';
export {default as AddPostIcon} from './add-post.svg';
export {default as UploadIcon} from './upload.svg';
export {default as GalleryIcon} from './gallery.svg';
export {default as CameraIcon} from './camera.svg';
export {default as DeleteIcon} from './delete.svg';
export {default as PlayIcon} from './playicon.svg';
export {default as PauseIcon} from './pauseicon.svg';
export {default as ProfileIcon} from './profile-avatar.svg';
export {default as Home6Filled} from './home-6-fill.svg';
export {default as Home6Outline} from './home-6-line.svg';
export {default as PostFilled1} from './post-filled1.svg'
export {default as PostOutLined1} from './post-outlined1.svg'
export {default as User3Filled} from './user-3-fill.svg'
export {default as User3Outline} from './user-3-line.svg'
export {default as ArrowLeftIcon} from './arrow-left-alt.svg'
export {default as ChevronLeftIcon } from './chevron-left-alt.svg'